name: PlayWithAnsible Demo
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    #services:
    #  cli:
    #    image: ghcr.io/playwithansible/playwithansible-cli:0.2.6
    #    options: --name cli
    steps:
      - run: docker run -t ghcr.io/playwithansible/playwithansible-cli:0.2.6 playwithansible version
